[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/p"
  to = "/.netlify/functions/p"
  status = 200
  force = true
[[redirects]]
  from = "/img.jpg"
  to = "/.netlify/functions/img"
  status = 200
  force = true
